# Generated by Django 5.1 on 2025-07-25 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notificacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('ACTIVIDAD_ASIGNADA', 'Actividad Asignada'), ('INSUMO_AGOTADO', 'Insumo Agotado'), ('INSUMO_CADUCANDO', 'Insumo Caducando'), ('PEST_ALERT', 'Alerta de Plagas'), ('HERRAMIENTA_EN_USO', 'Herramienta en Uso'), ('HERRAMIENTA_BAJA_STOCK', 'Herramienta Baja de Stock'), ('OTHER', 'Otro')], max_length=50),
        ),
    ]
