# Generated by Django 5.1 on 2025-04-03 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosechas', '0002_initial'),
        ('venta', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='precio',
        ),
        migrations.AddField(
            model_name='venta',
            name='fk_cosecha',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cosechas.cosecha'),
        ),
    ]
