# Generated by Django 5.1 on 2025-05-06 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosechas', '0002_initial'),
        ('insumos', '0010_tipoinsumo_insumo_es_compuesto_insumo_tipo_insumo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cosecha',
            name='unidades_de_medida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cosechas', to='insumos.unidadmedida'),
        ),
    ]
