# Generated by Django 5.1 on 2025-05-07 23:09

# Generated by Django 5.1 on 2025-05-07 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0007_prestamoinsumo_unidad_medida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='fecha_fin',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='fecha_inicio',
            field=models.DateTimeField(),
        ),
    ]
