FROM python:3.13

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN apt-get update && apt-get install -y \
    pkg-config \
    libmariadb-dev \
    gcc \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY Agrosis_API-dev/requirements.txt /app/
RUN pip install --upgrade pip && pip install -r requirements.txt

COPY Agrosis_API-dev/ /app/

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]