version: '3.8'
services:
  frontend:
    image: wmauriciodev/frontend_agrosoft:10
    ports:
      - "5173:80"
    stdin_open: true
    tty: true

  backend:
    image: wmauriciodev/backend_agrosoft:15
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      - POSTGRES_DB=agrosoft
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - DB_HOST=db
      - DB_PORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    command: >
      sh -c "python manage.py migrate &&
             daphne -b 0.0.0.0 -p 8000 Agrosoft.asgi:application"

  db:
    image: postgres:17
    restart: always
    environment:
      - POSTGRES_DB=agrosoft
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  documentacion:
    image: juan66016/agrosoft_documentacion:6
    ports:
      - "4321:4321"
    restart: unless-stopped

  manual:
    image: juan66016/agrosoft_manual:6
    ports:
      - "4322:4322"
    restart: unless-stopped

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --ignore-warnings ARM64-COW-BUG

volumes:
  postgres_data:
  redis_data: