name: Test Docker Compose on macOS
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Run Docker Compose
        run: |
          docker-compose up -d
          sleep 30
          curl -f http://localhost:5173 || exit 1
          curl -f http://localhost:8000 || exit 1
          curl -f http://localhost:4321 || exit 1
          curl -f http://localhost:4322 || exit 1
          docker-compose down