# Generated by Django 5.1 on 2025-05-27 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salario', '0004_alter_salario_options_salario_rol_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salario',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
