# Generated by Django 5.1 on 2025-04-03 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('especies', '0002_alter_especie_img_alter_especie_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrecioProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField()),
                ('nombre', models.CharField(max_length=100)),
                ('fk_especie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='especies.especie')),
            ],
            options={
                'db_table': 'precio_producto',
                'ordering': ['-fecha'],
            },
        ),
    ]
