# Generated by Django 5.1 on 2025-06-03 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0002_alter_lote_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lote',
            name='pos_x',
        ),
        migrations.RemoveField(
            model_name='lote',
            name='pos_y',
        ),
        migrations.AddField(
            model_name='lote',
            name='latitud',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lote',
            name='longitud',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lote',
            name='tam_x',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='lote',
            name='tam_y',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
