# Generated by Django 5.1 on 2025-02-22 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0001_initial'),
        ('usuario_rol', '0003_alter_usuariorol_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariorol',
            name='rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roles.roles'),
        ),
    ]
