# Generated by Django 5.1 on 2024-12-06 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bodega', '0003_initial'),
        ('insumos', '0003_initial'),
        ('semillero', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemilleroInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_necesaria', models.FloatField()),
                ('id_bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bodega.bodega')),
                ('id_insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insumos.insumo')),
                ('id_semillero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='semillero.semillero')),
            ],
        ),
    ]
