# Generated by Django 5.1 on 2025-05-06 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultivos', '0003_alter_cultivo_nombre'),
        ('insumos', '0010_tipoinsumo_insumo_es_compuesto_insumo_tipo_insumo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cultivo',
            name='unidad_de_medida',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='insumos.unidadmedida'),
            preserve_default=False,
        ),
    ]
