# Generated by Django 5.1 on 2025-05-19 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosechas', '0003_alter_cosecha_unidades_de_medida'),
        ('residuos', '0002_alter_residuo_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='residuo',
            name='id_cultivo',
        ),
        migrations.AddField(
            model_name='residuo',
            name='id_cosecha',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='residuos', to='cosechas.cosecha'),
            preserve_default=False,
        ),
    ]
