# Generated by Django 5.1 on 2025-05-25 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='puntomapa',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
