# Generated by Django 5.1 on 2025-06-03 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bancal', '0003_alter_bancal_lote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bancal',
            name='TamX',
        ),
        migrations.RemoveField(
            model_name='bancal',
            name='TamY',
        ),
        migrations.RemoveField(
            model_name='bancal',
            name='posX',
        ),
        migrations.RemoveField(
            model_name='bancal',
            name='posY',
        ),
        migrations.AddField(
            model_name='bancal',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='bancal',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='bancal',
            name='tam_x',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='bancal',
            name='tam_y',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
