# Generated by Django 5.1 on 2025-05-31 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensores', '0007_remove_sensor_unidad_medida_sensor_bancal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='device_code',
            field=models.CharField(blank=True, help_text='Código del dispositivo (p. ej. Arduino).', max_length=100, null=True),
        ),
    ]
