# Generated by Django 5.1.2 on 2024-12-06 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('aprendiz', 'Aprendiz'), ('pasante', 'Pasante'), ('instructor', 'Instructor'), ('administrador', 'Administrador')], max_length=20)),
                ('actualizacion', models.CharField(max_length=50)),
                ('fecha_creacion', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='rol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.roles'),
        ),
    ]
