# Generated by Django 5.1 on 2025-02-22 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rol_permiso', '0004_alter_rolpermiso_rol'),
        ('roles', '0001_initial'),
        ('roles_acciones', '0004_alter_rolaccion_rol'),
        ('usuario_rol', '0004_alter_usuariorol_rol'),
        ('usuarios', '0003_delete_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='rol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='roles.roles'),
        ),
        migrations.DeleteModel(
            name='Roles',
        ),
    ]
