# Generated by Django 5.1 on 2025-05-14 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_usuarios_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='numero_de_documento',
            field=models.IntegerField(null=True),
        ),
    ]
