# Generated by Django 5.1 on 2025-05-15 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0004_bodega_capacidad_bodega_ubicacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bodega',
            name='direccion',
        ),
    ]
