# Generated by Django 5.1 on 2025-05-02 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega_herramienta', '0007_remove_bodegaherramienta_cantidad_prestada'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodegaherramienta',
            name='cantidad_prestada',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
