# Generated by Django 5.1 on 2025-05-15 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega_insumo', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodegainsumo',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
