# Generated by Django 5.1 on 2025-03-12 19:19

from django.db import migrations

def create_initial_roles_and_permissions(apps, schema_editor):
    Roles = apps.get_model('roles', 'Roles')
    Permiso = apps.get_model('permisos', 'Permiso')

    # Crear roles
    roles = ['aprendiz', 'pasante', 'instructor', 'administrador']
    for rol in roles:
        Roles.objects.get_or_create(nombre=rol)

    # Crear permisos
    permisos = [
        {'nombre': 'ver_usuarios', 'descripcion': 'Puede ver usuarios'},
        {'nombre': 'editar_usuarios', 'descripcion': 'Puede editar usuarios'},
        {'nombre': 'eliminar_usuarios', 'descripcion': 'Puede eliminar usuarios'},
    ]
    for permiso in permisos:
        Permiso.objects.get_or_create(**permiso)

class Migration(migrations.Migration):
    dependencies = [
        ('roles', '0001_initial'), 
    ]
    operations = [
        migrations.RunPython(create_initial_roles_and_permissions),
    ]