# Generated by Django 5.1 on 2025-05-14 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0010_tipoinsumo_insumo_es_compuesto_insumo_tipo_insumo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumocompuesto',
            name='unidad_medida',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='insumos_compuestos', to='insumos.unidadmedida'),
        ),
    ]
