# Generated by Django 5.1 on 2025-05-14 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0011_insumocompuesto_unidad_medida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumocompuesto',
            name='unidad_medida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='insumos_compuestos', to='insumos.unidadmedida'),
        ),
        migrations.CreateModel(
            name='ConversionUnidad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('factor', models.DecimalField(decimal_places=4, max_digits=10)),
                ('unidad_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversiones_destino', to='insumos.unidadmedida')),
                ('unidad_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversiones_origen', to='insumos.unidadmedida')),
            ],
            options={
                'verbose_name': 'Conversión de Unidad',
                'verbose_name_plural': 'Conversiones de Unidades',
                'db_table': 'unidad_medida_conversion',
                'unique_together': {('unidad_origen', 'unidad_destino')},
            },
        ),
    ]
