# Generated by Django 5.1 on 2025-05-14 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0013_remove_insumocompuesto_unidad_medida_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insumo',
            name='es_compuesto',
        ),
        migrations.DeleteModel(
            name='InsumoCompuesto',
        ),
    ]
