# Generated by Django 5.1 on 2025-05-16 04:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0015_alter_insumo_cantidad'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('low_stock', 'Bajo Stock'), ('expiring', 'Caducidad')], max_length=20)),
                ('enviado', models.DateTimeField(default=django.utils.timezone.now)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insumos.insumo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Notificación',
                'verbose_name_plural': 'Registros de Notificaciones',
                'db_table': 'insumos_notificacionlog',
                'unique_together': {('insumo', 'tipo', 'user')},
            },
        ),
    ]
