# Generated by Django 5.1 on 2025-05-20 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cosechas', '0003_alter_cosecha_unidades_de_medida'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalisisCostoBeneficio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_calculo', models.DateTimeField(auto_now_add=True)),
                ('mano_obra', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('insumos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_costos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_ingresos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('rentabilidad', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('roi', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('cosecha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analisis_costo_beneficio', to='cosechas.cosecha')),
            ],
            options={
                'verbose_name': 'Análisis de Costo-Beneficio',
                'verbose_name_plural': 'Análisis de Costo-Beneficio',
                'ordering': ['-fecha_calculo'],
            },
        ),
    ]
