# Generated by Django 5.1 on 2025-07-31 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos_meteorologicos', '0009_alter_datos_metereologicos_fk_bancal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datos_metereologicos',
            name='calidad_aire',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='datoshistoricos',
            name='calidad_aire',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterModelTable(
            name='datos_metereologicos',
            table='datos_meteorologicos',
        ),
        migrations.AlterModelTable(
            name='datoshistoricos',
            table='datos_historicos',
        ),
    ]
