# Generated by Django 5.1 on 2025-05-31 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bancal', '0003_alter_bancal_lote'),
        ('datos_meteorologicos', '0008_datoshistoricos'),
        ('sensores', '0006_sensor_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos_metereologicos',
            name='fk_bancal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='datos_meteorologicos', to='bancal.bancal'),
        ),
        migrations.AlterField(
            model_name='datos_metereologicos',
            name='fk_sensor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='datos_meteorologicos', to='sensores.sensor'),
        ),
        migrations.AlterField(
            model_name='datoshistoricos',
            name='fk_bancal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='datos_historicos', to='bancal.bancal'),
        ),
        migrations.AlterField(
            model_name='datoshistoricos',
            name='fk_sensor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='datos_historicos', to='sensores.sensor'),
        ),
    ]
