# Generated by Django 5.1 on 2025-05-01 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0005_remove_actividad_cantidadusada_and_more'),
        ('bodega_herramienta', '0006_alter_bodegaherramienta_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamoherramienta',
            name='bodega_herramienta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bodega_herramienta.bodegaherramienta'),
        ),
    ]
