# Generated by Django 5.1 on 2025-05-07 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0006_prestamoherramienta_bodega_herramienta'),
        ('insumos', '0010_tipoinsumo_insumo_es_compuesto_insumo_tipo_insumo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamoinsumo',
            name='unidad_medida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='insumos.unidadmedida'),
        ),
    ]
