# Generated by Django 5.1 on 2025-05-19 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0008_alter_actividad_fecha_fin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamoherramienta',
            name='cantidad_devuelta',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='prestamoherramienta',
            name='cantidad_entregada',
            field=models.IntegerField(default=1),
        ),
    ]
