# Generated by Django 5.1 on 2025-05-27 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0003_alter_roles_nombre'),
        ('salario', '0003_rename_auxilio_transporte_salario_valorjornal_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salario',
            options={'ordering': ['-fecha_de_implementacion']},
        ),
        migrations.AddField(
            model_name='salario',
            name='rol',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='salarios', to='roles.roles'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='salario',
            unique_together={('rol', 'fecha_de_implementacion')},
        ),
    ]
