# Generated by Django 5.1 on 2025-05-14 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0012_alter_insumocompuesto_unidad_medida_conversionunidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insumocompuesto',
            name='unidad_medida',
        ),
        migrations.DeleteModel(
            name='ConversionUnidad',
        ),
    ]
