# Generated by Django 5.1 on 2025-05-15 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0014_remove_insumo_es_compuesto_delete_insumocompuesto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
