# Generated by Django 5.1 on 2025-05-16 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0016_notificacionlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotificacionLog',
        ),
    ]
