# Generated by Django 5.1 on 2025-04-30 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herramientas', '0004_herramienta_fecha_registro'),
    ]

    operations = [
        migrations.AddField(
            model_name='herramienta',
            name='precio',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
