# Generated by Django 5.1 on 2025-05-31 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bancal', '0003_alter_bancal_lote'),
        ('sensores', '0006_sensor_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='unidad_medida',
        ),
        migrations.AddField(
            model_name='sensor',
            name='bancal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sensores', to='bancal.bancal'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='device_code',
            field=models.CharField(blank=True, help_text='Código único del dispositivo (p. ej. Arduino).', max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='sensor',
            name='medida_maxima',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='sensor',
            name='medida_minima',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='tipo_sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sensores', to='sensores.tiposensor'),
        ),
    ]
