# Generated by Django 5.1 on 2025-05-02 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controles', '0002_rename_id_afeccion_control_afeccion_and_more'),
        ('insumos', '0010_tipoinsumo_insumo_es_compuesto_insumo_tipo_insumo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insumos.insumo'),
        ),
    ]
