# Generated by Django 5.1 on 2024-12-06 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sensores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VelocidadViento',
            fields=[
                ('sensorabs_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sensores.sensorabs')),
                ('velocidadKmH', models.IntegerField()),
            ],
            bases=('sensores.sensorabs',),
        ),
    ]
