# Generated by Django 5.1 on 2025-05-16 02:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bodega', '0005_remove_bodega_direccion'),
        ('precio_producto', '0006_alter_precioproducto_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BodegaPrecioProducto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bodegas_precios_productos', to='bodega.bodega')),
                ('creador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bodega_precios_productos_creados', to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_bodegas', to='precio_producto.precioproducto')),
            ],
            options={
                'verbose_name': 'Bodega Precio Producto',
                'verbose_name_plural': 'Bodega Precios Productos',
            },
        ),
    ]
