# Generated by Django 5.1 on 2025-05-16 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega_precio_producto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodegaprecioproducto',
            name='cantidad',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
